### ISSUE TITLE
cannot load such file -- launchy (LoadError)

### ISSUE THREAD

**Issue by shayanzare** [larsch/ocra#121]
Hello!
i require launchy for open browser but after ruby to exe show this error ::
```
C:/Users/virus007/AppData/Local/Temp/ocr3C75.tmp/lib/ruby/2.3.0/rubygems/core_ex
t/kernel_require.rb:55:in `require': cannot load such file -- launchy (LoadError)
      from C:/Users/virus007/AppData/Local/Temp/ocr3C75.tmp/lib/ruby/2.3.0/rub
ygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Users/virus007/AppData/Local/Temp/ocr3C75.tmp/src/payload.rb:4:in `<main>'
```

my command is 
```bash
ocra payload.rb --add-all-core --gem-full --no-dep-run --output payload.exe
```

Please Help!
Thanks!

**Comment by larsch** [comment]
Ocra has no knowledge that you are using the launchy Gem when you specify `--no-dep-run`. You need to run without this option or manually specify the location of all the files in the Gem's you need.
