### ISSUE TITLE
Missing gems despite being present in gemfile

### ISSUE THREAD

**Issue by CreeperLava** [larsch/ocra#135]
I ran the following command : `ocra --no-dep-run --no-enc --gemfile Gemfile texture_mapper.rb`

Here is my gemfile : `source 'https://rubygems.org'

gem 'fileutils'
gem 'sqlite3'
gem 'gtk3'
gem 'http'
gem 'csv'`

And here is the output I get when I try to run the executable :
```
> texture_mapper.exe
C:/Users/w42/AppData/Local/Temp/ocr2F30.tmp/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- fileutils (LoadError)
        from C:/Users/w42/AppData/Local/Temp/ocr2F30.tmp/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Users/w42/AppData/Local/Temp/ocr2F30.tmp/src/texture_mapper.rb:1:in `<main>'
```

Any help would be appreciated.

**Comment by thisismydesign** [comment]
Try without `--no-dep-run`.

**Comment by thisismydesign** [comment]
This might also help you: https://github.com/karhatsu/hello-ocra

**Comment by CreeperLava** [comment]
Thank you for the answer. I've given up on Ruby executables since then and just use C++ Qt now. Hopefully some day it will be implemented in the language itself.
