### ISSUE TITLE
The specified module could not be found "gosu.so"

### ISSUE THREAD

**Issue by fguillen** [larsch/ocra#181]
I found gosu.so here: `C:\Ruby31-x64\lib\ruby\gems\3.1.0\gems\gosu-1.4.1\lib\gosu.so`

This is the ocra command I am executing: 
```
ocra game.rb --dll ruby_builtin_dlls\libssp-0.dll --dll ruby_builtin_dlls\libgmp-10.dll --gem-full=gosu,fantasy --gemfile Gemfile
```

On this ruby code: https://github.com/fguillen/RubyInFantasyGames/tree/main/InTheBeach

And this is the error: 

```
<internal:C:/Users/fg/AppData/Local/Temp/ocr8692.tmp/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': 126: The specified module could not be found.   - C:/Users/fg/AppData/Local/Temp/ocr8692.tmp/lib/ruby/gems/3.1.0/gems/gosu-1.4.1/lib/gosu.so (LoadError)
        from <internal:C:/Users/fg/AppData/Local/Temp/ocr8692.tmp/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from C:/Users/fg/AppData/Local/Temp/ocr8692.tmp/lib/ruby/gems/3.1.0/gems/gosu-1.4.1/lib/gosu.rb:22:in `<top (required)>'
        from <internal:C:/Users/fg/AppData/Local/Temp/ocr8692.tmp/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:C:/Users/fg/AppData/Local/Temp/ocr8692.tmp/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from C:/Users/fg/AppData/Local/Temp/ocr8692.tmp/lib/ruby/gems/3.1.0/gems/fantasy-0.1.3/lib/fantasy.rb:2:in `<top (required)>'
        from <internal:C:/Users/fg/AppData/Local/Temp/ocr8692.tmp/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `require'
        from <internal:C:/Users/fg/AppData/Local/Temp/ocr8692.tmp/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
        from <internal:C:/Users/fg/AppData/Local/Temp/ocr8692.tmp/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
        from C:/Users/fg/AppData/Local/Temp/ocr8692.tmp/src/game.rb:1:in `<main>'
<internal:C:/Users/fg/AppData/Local/Temp/ocr8692.tmp/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- fantasy (LoadError)
        from <internal:C:/Users/fg/AppData/Local/Temp/ocr8692.tmp/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from C:/Users/fg/AppData/Local/Temp/ocr8692.tmp/src/game.rb:1:in `<main>'
```

How can I ask ocra to include the `gosu.so`  in the package?

**Comment by fguillen** [comment]
This command ended working: 

```
ocra my_ruby_game.rb --windows --dll ruby_builtin_dlls\libssp-0.dll --dll ruby_builtin_dlls\libgmp-10.dll --dll ruby_builtin_dlls\libgcc_s_seh-1.dll --dll ruby_builtin_dlls\libwinpthread-1.dll
```
