### ISSUE TITLE
Executable created with Ocra and Ruby 3.2.2 throw an error 

### ISSUE THREAD

**Issue by silkPK** [larsch/ocra#193]
Executable generated with last gem Ocra 1.3.11 and Ruby 3.2.2 return following error 

C:/Users/x/AppData/Local/Temp/ocrFBB1.tmp/lib/ruby/site_ruby/3.2.0/rubygems.rb:1368:in `read': No such file or directory @ rb_sysopen - C:/Users/x/AppData/Local/Temp/ocrFBB1.tmp/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb (Errno::ENOENT)
        from C:/Users/x/AppData/Local/Temp/ocrFBB1.tmp/lib/ruby/site_ruby/3.2.0/rubygems.rb:1368:in `<top (required)>'
        from <internal:gem_prelude>:2:in `require'
        from <internal:gem_prelude>:2:in `<internal:gem_prelude>'

**Comment by z3nnix** [comment]
ocra is designed for older versions of ruby and therefore it doesn't work, but you can use an ocra fork called ocra2

https://rubygems.org/gems/ocra2

**Comment by Largo** [comment]
ocra2 seemed interesting but they still haven't created a github repo. I made a new fork called ocran, which also fixes a new problem with the new rubygems, where kernel_require.rb was not in the load path. 
Considering that the gem contains binary files, I also plan to only create gems from github actions for security.

Thanks to all contributors for this great project.

https://github.com/largo/ocran

Edit: Just reread the issue. It's exactly what I fixed in the fork. I'm still testing and trying to improve the gem with all the fixes that I have available (innosetup for instance), so let me now in the issues if anything in the fork does not work.
