### ISSUE TITLE
Unable to create an exe for a .rb script using ocra

### ISSUE THREAD

**Issue by nandish20** [larsch/ocra#94]
Currently i have 1.9.3 ruby version. But i am facing the below mentioned issue even in the 2.0.0 and 2.1.6. I have a very simple ruby script which open a browser and then fills a url. I just wanted to know how exactly ocra works so that i can implement this in my project. I am able to create the exe file using the Ocra script.rb command, but when i run the executable i am getting the below mentioned error

"[WARNING] MultiJson is using the default adapter (ok_json).We recommend loading a different JSON library to improve performance.
C:/Users/ADMINI~1/AppData/Local/Temp/ocrED.tmp/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': Did not recognize your adapter specification (cannot load such file -- multi_json/adapters/ok_json). (MultiJson::AdapterError)
        from C:/Users/ADMINI~1/AppData/Local/Temp/ocrED.tmp/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from C:/Users/ADMINI~1/AppData/Local/Temp/ocrED.tmp/lib/ruby/gems/1.9.1/gems/multi_json-1.11.0/lib/multi_json.rb:153:in `load_adapter_from_string_name'
        from C:/Users/ADMINI~1/AppData/Local/Temp/ocrED.tmp/lib/ruby/gems/1.9.1/gems/multi_json-1.11.0/lib/multi_json.rb:98:in `load_adapter'
        from C:/Users/ADMINI~1/AppData/Local/Temp/ocrED.tmp/lib/ruby/gems/1.9.1/gems/multi_json-1.11.0/lib/multi_json.rb:100:in `load_adapter'
        from C:/Users/ADMINI~1/AppData/Local/Temp/ocrED.tmp/lib/ruby/gems/1.9.1/gems/multi_json-1.11.0/lib/multi_json.rb:90:in `use'
        from C:/Users/ADMINI~1/AppData/Local/Temp/ocrED.tmp/lib/ruby/gems/1.9.1/gems/multi_json-1.11.0/lib/multi_json.rb:72:in `adapter'
        from C:/Users/ADMINI~1/AppData/Local/Temp/ocrED.tmp/lib/ruby/gems/1.9.1/gems/multi_json-1.11.0/lib/multi_json.rb:130:in `current_adapter'
        from C:/Users/ADMINI~1/AppData/Local/Temp/ocrED.tmp/lib/ruby/gems/1.9.1/gems/multi_json-1.11.0/lib/multi_json.rb:117:in `load'
        from C:/Users/ADMINI~1/AppData/Local/Temp/ocrED.tmp/lib/ruby/gems/1.9.1/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/common/json_helper.rb:11:in `json_load'
        from C:/Users/ADMINI~1/AppData/Local/Temp/ocrED.tmp/lib/ruby/gems/1.9.1/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/firefox/profile.rb:30:in `default_preferences'
        from C:/Users/ADMINI~1/AppData/Local/Temp/ocrED.tmp/lib/ruby/gems/1.9.1/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/firefox/profile.rb:222:in `update_user_prefs_in'
        from C:/Users/ADMINI~1/AppData/Local/Temp/ocrED.tmp/lib/ruby/gems/1.9.1/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/firefox/profile.rb:79:in `layout_on_disk'
        from C:/Users/ADMINI~1/AppData/Local/Temp/ocrED.tmp/lib/ruby/gems/1.9.1/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/firefox/launcher.rb:58:in `create_profile'
        from C:/Users/ADMINI~1/AppData/Local/Temp/ocrED.tmp/lib/ruby/gems/1.9.1/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/firefox/launcher.rb:34:in `block in launch'
        from C:/Users/ADMINI~1/AppData/Local/Temp/ocrED.tmp/lib/ruby/gems/1.9.1/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/firefox/socket_lock.rb:20:in `locked'
        from C:/Users/ADMINI~1/AppData/Local/Temp/ocrED.tmp/lib/ruby/gems/1.9.1/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/firefox/launcher.rb:32:in `launch'
        from C:/Users/ADMINI~1/AppData/Local/Temp/ocrED.tmp/lib/ruby/gems/1.9.1/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/firefox/bridge.rb:24:in `initialize'
        from C:/Users/ADMINI~1/AppData/Local/Temp/ocrED.tmp/lib/ruby/gems/1.9.1/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/common/driver.rb:31:in `new'
        from C:/Users/ADMINI~1/AppData/Local/Temp/ocrED.tmp/lib/ruby/gems/1.9.1/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/common/driver.rb:31:in `for'
        from C:/Users/ADMINI~1/AppData/Local/Temp/ocrED.tmp/lib/ruby/gems/1.9.1/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver.rb:67:in `for'
        from C:/Users/ADMINI~1/AppData/Local/Temp/ocrED.tmp/lib/ruby/gems/1.9.1/gems/watir-webdriver-0.7.0/lib/watir-webdriver/browser.rb:46:in `initialize'
        from C:/Users/ADMINI~1/AppData/Local/Temp/ocrED.tmp/src/testexe.rb:5:in `new'
        from C:/Users/ADMINI~1/AppData/Local/Temp/ocrED.tmp/src/testexe.rb:5:in `<main>'"

I am not sure of how to debug this issue. Could you please help me with this. Thanks in advance.

**Comment by lmayorga1980** [comment]
what is the command line that you use?

**Comment by nandish20** [comment]
I just use the command “ocra script.rb”

Regards,
Nandish Shetty
QA

nandishshetty@air-watch.com
www.air-watch.com<http://www.air-watch.com/>
[cid:3420106421_29290231]
This communication is confidential and is intended to be privileged pursuant to applicable law. If you are not a designated recipient of this message, please do not read, copy, use or disclose this message or its attachments. Notify the sender by replying to this message and delete or destroy all copies of this message and attachments in all media. Thank you.

**Comment by lmayorga1980** [comment]
Not sure if this will help but the one I use is 

` ocra --quiet --console <ruby_script.rb>`

**Comment by nandish20** [comment]
I tried the command which you had suggested but I am still getting the same error.

Regards,
Nandish Shetty
QA

nandishshetty@air-watch.com
www.air-watch.com<http://www.air-watch.com/>
[cid:3420106421_29290231]
This communication is confidential and is intended to be privileged pursuant to applicable law. If you are not a designated recipient of this message, please do not read, copy, use or disclose this message or its attachments. Notify the sender by replying to this message and delete or destroy all copies of this message and attachments in all media. Thank you.
